### ISSUE TITLE
FR: Disable > in the template

### ISSUE THREAD

**Issue by isle9** [ka1tzyu/local-quotes#16]
Let the user choose themselves in the settings if they want to include > or not in the template. Currently > is automatically added and there's no way to disable it. I'd like to disable it because it unnecessarily indents my block.

**Comment by ka1tzyu** [comment]
Yeah, understood, it's really unnecessary, I will fix it asap (maybe today)

**Comment by ka1tzyu** [comment]
If you're satisfied with the functionality, close the issue as completed. Otherwise, tell why you are not.

**Comment by isle9** [comment]
Works great, cheers!
