### ISSUE TITLE
What does refresh do?

### ISSUE THREAD

**Issue by bencodesall** [ka1tzyu/local-quotes#17]
The doc simply states

> ### 🔃 Refresh intervals
> refresh property uses custom moment.js like syntax. There are all possible variants (case-sensitive):
> 
> - 10s - equals 10 seconds
> - 10m - equals 10 minutes
> - 10h - equals 10 hours
> - 2d - equals 2 days
> - 2w - equals 2 weeks
> - 2M - equals 2 months
> - 1y - equals 1 year

It is note immediately clear what this refresh refers to in the context of quotes. Perhaps the readme could provide a bit more description around that. Great stuff!

**Comment by ka1tzyu** [comment]
@bencodesall Hi! Refresh interval is the time between refreshes of your quote block (change author and quote text corresponding to `search` field). If it's more clear description, I can add it to README

**Comment by ka1tzyu** [comment]
You can see small description in the [section above](https://github.com/ka1tzyu/local-quotes#%EF%B8%8F-making-quote-block-by-yourself)

**Comment by isle9** [comment]
@ka1tzyu How about adding a command to manually refresh the quote inside the code block?

**Comment by ka1tzyu** [comment]
@isle9 If it's your future request, create another issue and describe your idea there

**Comment by ka1tzyu** [comment]
@bencodesall did you get your answer?
