### ISSUE TITLE
FR: Add a way to manually refresh the code block

### ISSUE THREAD

**Issue by isle9** [ka1tzyu/local-quotes#18]
Preferably inside the code block itself. For instance, add an icon in one of the top corners which will refresh the code block when clicked.

**Comment by ka1tzyu** [comment]
I had the same idea, but left it because it is a little hard for me. But if not only I think about it, I'll try to do this as soon as possible

**Comment by isle9** [comment]
You could just add a command to manually refresh code blocks inside the current not for now. That should be simple enough.

**Comment by ka1tzyu** [comment]
@isle9 I added a new command `Refresh local quotes for active file` in the [1.5.0]. Update and check it out!

If it's exactly what you wanted to, please, close this issue as completed.

**Comment by isle9** [comment]
The new command does exactly what I wanted it to do. Seems to work great. Ideally, there would be an icon in the code block or something similar to just refresh that block without the need to use commands. You can close this issue if you're not planning to do any more work on this.

**Comment by ka1tzyu** [comment]
Ok, I'll try to do something like this

**Comment by ka1tzyu** [comment]
@isle9 Check out the new refresh button from [1.6.0](https://github.com/ka1tzyu/local-quotes/releases/tag/1.6.0)

**Comment by isle9** [comment]
> @isle9 Check out the new refresh button from [1.6.0](https://github.com/ka1tzyu/local-quotes/releases/tag/1.6.0)

Works great!

Although, in my theme (Minimal), it was a bit too far down for me. So I've set the top and right to 0px.

You might want to add am option to choose the side on which the icon should be displayed because in the default Obsidian theme, the icon is directly bellow the code block edit icon and can't be clicked on.

You can close this issue if you think you're done with it and thanks for writing the plugin!

**Comment by ka1tzyu** [comment]
I will improve buttons, but closing the issue

**Comment by ka1tzyu** [comment]
> > @isle9 Check out the new refresh button from [1.6.0](https://github.com/ka1tzyu/local-quotes/releases/tag/1.6.0)
> 
> Works great!
> 
> Although, in my theme (Minimal), it was a bit too far down for me. So I've set the top and right to 0px.
> 
> You might want to add am option to choose the side on which the icon should be displayed because in the default Obsidian theme, the icon is directly bellow the code block edit icon and can't be clicked on.
> 
> You can close this issue if you think you're done with it and thanks for writing the plugin!

@isle9 I've released a new [1.7.0](https://github.com/ka1tzyu/local-quotes/releases/tag/1.7.0) with nice integration with `Style Settings` plugin. There you can choose one of the 4 corners, padding from them and refresh icon size
